name: SOP Watch

on:
  schedule:
    - cron: "15 2 * * *"   # nightly 02:15 UTC
  workflow_dispatch: {}

jobs:
  check-sops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run SOP Watch
        run: python scripts/sop_watch.py
