name: Tool Import Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    name: Import tools from tools.yaml
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure PyYAML present for the test script
          python - <<'PY'
          try:
              import yaml  # noqa
          except Exception:
              import sys, subprocess
              subprocess.check_call([sys.executable, "-m", "pip", "install", "pyyaml"])
          PY

      - name: 🧪 Run smoke test
        run: |
          python scripts/test_imports.py
