name: Repo Health

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      # ---- Lint (flake8) ----
      - name: Run linting (flake8 - report only)
        run: |
          python -m pip install flake8 || true
          flake8 . \
            --count --select=E9,F63,F7,F82 \
            --show-source --statistics \
            --exit-zero || true

      # ---- Types (mypy) ----
      - name: Run type checks (mypy - report only)
        run: |
          python -m pip install mypy || true
          mypy . \
            --config-file mypy.ini \
            --ignore-missing-imports \
            --no-error-summary \
            --pretty || true
