name: Repo Health

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ fix/tool-hello-canonicalize ]

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyyaml
      - name: Write build meta (for sidebar)
        run: |
          mkdir -p streamlit_app
          echo "{\"sha\":\"$GITHUB_SHA\",\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > streamlit_app/.build-meta.json
      - name: Health: import app and run filtered smoke
        env:
          TOOLS_FILTER: hello
        run: |
          python scripts/health_app.py
