name: PR Nurse

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  review:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gather diff
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff origin/${{ github.base_ref }}...HEAD --unified=0 > diff.txt

      - name: Build prompt
        run: |
          echo 'You are PR Nurse. Review this Git diff. Identify bugs, security issues, duplicated logic, and missing tests. Propose exact unit test names and snippets. Finish with a merge checklist.' > prompt.txt
          echo '--- DIFF START ---' >> prompt.txt
          head -c 150000 diff.txt >> prompt.txt
          echo '\n--- DIFF END ---' >> prompt.txt

      - name: Ask OpenAI for review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
import os, json, urllib.request
prompt = open('prompt.txt','r',encoding='utf-8',errors='ignore').read()
data = json.dumps({
  "model": "gpt-4o-mini",
  "messages": [{"role":"user","content": prompt}],
  "temperature": 0.2,
  "max_tokens": 800
}).encode()
req = urllib.request.Request(
  "https://api.openai.com/v1/chat/completions",
  data=data,
  headers={"Authorization":"Bearer "+os.environ["OPENAI_API_KEY"],
           "Content-Type":"application/json"}
)
resp = urllib.request.urlopen(req).read().decode()
text = json.loads(resp)["choices"][0]["message"]["content"]
open("review.md","w",encoding="utf-8").write(text)
PY

      - name: Post review comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: review.md
