name: Repo Health Check

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run repo health report
        run: |
          python scripts/health_report.py --tools-yaml tools.yaml --tools-dir streamlit_app/tools --package-root streamlit_app --out-md repo-health-report.md --out-json repo-health-report.json

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-health-report
          path: |
            repo-health-report.md
            repo-health-report.json

      - name: Surface summary
        if: always()
        run: |
          echo "## Repo Health Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f repo-health-report.md ]; then
            cat repo-health-report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "_No report generated._" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Fail if problems found
        run: |
          python - << 'PY'
          import json, sys, pathlib
          p = pathlib.Path("repo-health-report.json")
          if not p.exists():
              print("No JSON report found; failing.")
              sys.exit(1)
          data = json.loads(p.read_text())
          if data.get("failed_checks", 0) > 0:
              print(f"Failed checks: {data['failed_checks']}")
              sys.exit(1)
          print("All checks passed.")
          PY
