name: Repo Doctor

on:
  push:
    branches: [ main, ci/* ]
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * 1"  # weekly, Mon 05:17 UTC

jobs:
  doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Validate required files exist
        run: |
          set -euo pipefail
          echo "Repo Health"
          echo "------------"

          required_files=(
            ".github/workflows/health.yml"
            ".github/workflows/repo_doctor.yml"
            "scripts/test_imports.py"
            "README.md"
            "LICENSE"
          )

          missing=0
          for f in "${required_files[@]}"; do
            if [ -e "$f" ]; then
              printf "OK    %s\n" "$f"
            else
              printf "MISSING %s\n" "$f" >&2
              missing=1
            fi
          done

          # Print last commit info for visibility
          echo
          echo "Last commit:"
          git log -1 --pretty=oneline || true

          exit $missing

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install minimal deps (best effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pyyaml
          fi

      - name: Run import smoke (non-blocking if empty)
        run: |
          set -e
          if [ -f scripts/test_imports.py ]; then
            python scripts/test_imports.py --allow-empty
          else
            echo "scripts/test_imports.py not found; skipping smoke."
          fi
